### ISSUE TITLE
Not an issue , just an argument

### ISSUE THREAD

**Issue by shehramjamil** [happysingh23828/Android-Clean-Architecture#10]
As you implemented the clean code architecture along with MVVM,
Android architecture pattern which is based on repository classes is similar to the clean code interactors or use case classes. Because the repository implementation classes contains all the remote or local database handling, why we can't just call the repository classes in the view model instead of creating an extra layer of use cases and just calling those repository functions from use cases and putting that use cases into the view model.
If we worry about the separation of concerns then we can make separate repositories for one view model if a different data model is needed for a single UI.
A repo. instance deals with single source of data as per google recommendation so I assume that creating use cases is an extra layer. Please share your thoughts on it.

**Comment by happysingh23828** [comment]
Thank @shehramjamil  for bringing up this, I got the same thought while implementing this architecture. and as you already explained that repository is only responsible for data.

More Specific
- **Repositories** are the data layer in which you store and access data.
- **UseCases** handles your business logic who decides how your data should be manipulated for a specific scenario or for a use case. it simply holds dataflow logic.

UseCases can be a more complicated business logic or you want to use this logic in other view models/presenters. So with Use-Cases, you make your business code re-usable and avoid code duplication in your view models/presenters. Later, if you want to decide to change your business logic you only change your use-case, not all the view models.

In our current App requirements, we only need to show a list of data to screen, so our UseCases are not having much business logic in them, they are only calling repository functions nothing else. but things got complicated when you have more conditions and dataflow in your requirements.

For more details and real examples, you can [refer to this blog](https://proandroiddev.com/why-you-need-use-cases-interactors-142e8a6fe576).

**Comment by shehramjamil** [comment]
Well Understood.
Thanks for referring to the blog and if we combine co routines with it instead of RxJava/kotlin then many lines of code and callbacks can be avoided.
Re-usability is the biggest flex of use cases  :100:

**Comment by happysingh23828** [comment]
Yes, using co-routines will reduce the code, will try to update the code. Thanks :+1:
